name: Deploy wasm4 game

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0
      - run: zig build

      - name: Set up bun
        uses: oven-sh/setup-bun@v1
        with:
          version: 0.8.0
      - name: Install w4
        run: bun install wasm4
      - name: Bundle cart into html
        run: node_modules/wasm4/cli.js bundle zig-out/lib/cart.wasm --title speen --html index.html --description "vector demo"

      - name: Configure pages
        uses: actions/configure-pages@v3
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'
      - name: Deploy pages
        uses: actions/deploy-pages@v2
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
